type Difficulty = "Easy" | "Medium" | "Advanced";
export interface CocktailDataProps {
  id: string;
  title: string;

  description: string;
  ingredients: string[];
  imageUrl: string;
  difficulty: Difficulty;
  category: string;
  base: string;
  method: string;
  garnish: string;
}

export const cocktailsData: CocktailDataProps[] = [
  {
    id: "1",
    title: "Himalyan Negroni",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "30ml Hapusa Gin",
      "Timbur (Himalayan Sichuan Pepper) Infused",
      "15ml Vermouth",
      "15ml Campari",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Gin",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "2",
    title: "Apricot Smash",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/cocktails/apricot-smash.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Gin",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "3",
    title: "Himalyan Gimlet",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/cocktails/gimlet.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Gin",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "4",
    title: "NY Sour",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/cocktails/nysour.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "5",
    title: "Southside",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "6",
    title: "Greater Martini",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "7",
    title: "Greater Gin Basil Smash",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "8",
    title: "Greater Salty Dog",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "9",
    title: "Colonial Cocktail",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "10",
    title: "Maratonic",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "11",
    title: "Aviation",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "12",
    title: "Morlacco Fizz",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "13",
    title: "Cherry Negoni",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "14",
    title: "Luxi Style",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "5",
    title: "Southside",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "5",
    title: "Southside",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "5",
    title: "Southside",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "5",
    title: "Southside",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "5",
    title: "Southside",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
  {
    id: "5",
    title: "Southside",
    description: "A timeless cocktail made with Gin, and sugar.",
    ingredients: [
      "2 oz Bourbon or Rye Whiskey",
      "1 Sugar Cube",
      "2-3 dashes Angostura Bitters",
      "Orange Peel for garnish",
      "Ice Cubes",
    ],
    imageUrl: "/sula/featuredHapusa.jpg",
    difficulty: "Easy",
    category: "Classic",
    base: "Whiskey",
    method: "Stir all ingredients with ice and strain into a chilled glass.",
    garnish: "Orange peel",
  },
];
