export interface Bottle {
  id: number;
  slug: string;
  name: string;
  description: string;
  img: string;
  volume: string;
  grapeVarietal?: string;
  category: string;
  country: string;
  flavors: string;
  pairings: string[];
  highlights: string[];
  alcoholPercentage?: string;
}
export const FeaturedProduct = [
  {
    id: 1,
    name: "Hapusa Himalayan Dry Gin",
    img: "/sula/featuredHapusa.jpg",
    slug: "hapusa-himalayan-dry-gin",
    category: "gin",
    description:
      "Hapusa is a premium Himalayan dry gin, distilled with foraged botanicals from the region, creating a bold and aromatic spirit. Juniper, known as Hapusa in Sanskrit, is what gives their gin its name as well as its wild smell and scent.  This scarce juniper berry, which grows close to the Himalayan snow line, offers a lovely framework around which the other botanicals are thoughtfully placed. To create a true voyage in a glass, these botanicals are imported from all around the nation, combining its many flavours, cuisines, and civilisations.  Your taste sensations go through the monsoon forests of Tamil Nadu, the banks of the Hooghly River, the pine forests of the Himalayas, and the verdant spice plantations of Goa.",

    background: "/backgrounds/Hapusa-Gin-lifestyle.jpeg",
  },
  {
    id: 2,
    name: "Greater Than London Dry Gin",
    img: "/sula/greaterThanFeatured.jpg",
    slug: "greater-than-london-dry-gin",
    category: "gin",
    description:
      "Greater Than is India’s first craft gin, featuring juniper-forward flavors with hints of citrus and spice, perfect for refreshing cocktails.",
  },
  {
    id: 3,
    name: "Luxardo Maraschino Orginale",
    img: "/sula/featuredLux.png",
    slug: "luxardo-maraschino-originale",
    category: "liquer",
    description:
      "Chenin Blanc is a refreshing white wine known for its bright acidity and tropical fruit flavors. Perfect for warm summer days.",
  },
  {
    id: 4,
    name: "Luxardo Bitter Rosse",
    img: "/sula/featuredBitter.png",
    slug: "luxardo-bitter-rosse",
    category: "liquer",
    description:
      "Shiraz Cabernet is a bold red wine with deep berry flavors, balanced tannins, and a rich, full-bodied texture.",
  },
  {
    id: 5,
    name: "Sula Tropical Rose",
    img: "/sula/tropicalFeature.jpg",
    slug: "sula-tropical-rose",
    category: "wines",
    description: "A refreshing and fruity rosé wine, perfect for summer days.",
  },
];

export const Bottles = [
  {
    id: 1,
    name: "Hapusa Himalayan Dry Gin",
    img: "/home/hapusa.png",
    slug: "hapusa-himalayan-dry-gin",
    description:
      "Hapusa is a premium Himalayan dry gin, distilled with foraged botanicals from the region, creating a bold and aromatic spirit. Juniper, known as Hapusa in Sanskrit, is what gives their gin its name as well as its wild smell and scent.  This scarce juniper berry, which grows close to the Himalayan snow line, offers a lovely framework around which the other botanicals are thoughtfully placed. To create a true voyage in a glass, these botanicals are imported from all around the nation, combining its many flavours, cuisines, and civilisations.  Your taste sensations go through the monsoon forests of Tamil Nadu, the banks of the Hooghly River, the pine forests of the Himalayas, and the verdant spice plantations of Goa.",

    background: "/backgrounds/Hapusa-Gin-lifestyle.jpeg",
    category: "gin",
    country: "India",
    flavors:
      "Hapusa is a sipping Gin best appreciated straight from the freezer. Expect pine forests and wildflowers on the nose with a bold earthiness on the palate and a long, delicately spiced, finish",
    pairings: [],
    highlights: [
      "made with Juniper form the Himalayas",
      "Along with Coriander Seeds, Tumeric, Ginger, Gondhoraj, Mango",
      "And Almonds",
    ],
    volume: "750ml",
    alcoholPercentage: "43%",
  },
  {
    id: 2,
    name: "Greater Than London Dry Gin",
    img: "/home/greaterthan.png",
    slug: "greater-than-london-dry-gin",
    description:
      "GIN, BUT GREATER! The first-ever London Dry Gin made in India. Copper pot distilled with botanicals sourced from India and around the world. This gin has clean juniper and fresh lemon peel on the nose and a zing of ginger on the finish. Distilled in Goa with nine unique botanicals: Juniper berries, Coriander seeds, Almond, Angelica root, Fennel, Lemongrass, Orange peel, Chamomile & Ginger.",
    category: "gin",
    country: "India",
    flavors:
      "Clean Juniper with Fresh Lemon Peel on the nose and a zing of ginger on the finish",
    pairings: [],
    highlights: [],
    volume: "750ml",
    alcoholPercentage: "70cl 40% abv",
  },
  {
    id: 3,
    name: "Sula Chenin Blanc",
    img: "/sula/cheninBlanc.png",
    slug: "sula-chenin-blanc",
    description:
      "A refreshing and easy-drinking white wine, with some residual sugar, which gives it a slight sweetness, smartly balanced by its delightful acidity. A beautiful Chenin Blanc.This Chenin Blanc wine has been made with the most ultimate respect for the environment, following strict sustainable practices. Come discover our beautiful vineyard, our Tasting Room and our gorgeous boutique hotel The Source, in the rolling hills of Nashik Valley. ",
    category: "wines",
    country: "India",
    flavors: "Ripe Tropical Fruit and Hints of Honey",
    pairings: ["Salad, Gujarati Thali", "Vegetable Quiche, Rawa Fried Fish"],
    highlights: [
      "India's Best Selling White Wine",
      "An easy drinking off-dry white wine",
      "Great to offer to first time wine drinkers",
    ],
    volume: "750ml",
    grapeVarietal: "100% Chenin Blanc",
  },
  {
    id: 4,
    name: "Sula Late Harvest",
    img: "/sula/lateharvest.png",
    slug: "sula-late-harvest",
    category: "wines",
    description:
      "Bask in Sula’s Late Harvest Chenin Blanc, the first Indian wine to win Silver at the Paris Wine Cup and Decanter World Wine Awards. Sweet and rich, with notes of honey, this wine is a true delight for the palate. This dessert wine has been made with the most ultimate respect for the environment, following strict sustainable practices. Come discover our beautiful vineyard, our Tasting Room and our gorgeous boutique hotel The Source, in the rolling hills of Nashik Valley.",
    country: "India",
    flavors: "Rich aromas of apricot, mango, raisins with luscious acidity.",
    pairings: [
      "Cheese cake, panna cotta",
      "gubani-ka-meetha",
      "gulab jamun, blue cheese",
    ],
    highlights: [
      "India’s most loved dessert wine",
      "Very aromatic and the first ever Late Harvest Chenin Blanc of India",
    ],
    volume: "750ml",
    grapeVarietal: "85% Chenin Blanc, 15% Muscat",
  },
  {
    id: 5,
    name: "Sula Shiraz Cabernet",
    img: "/sula/shirazCabernet.png",
    slug: "sula-shiraz-cabernet",
    category: "wines",
    description:
      "Silky and earthy, this Shiraz Cabernet is packed with dark cherries, pepper and mocha notes. A super food-friendly wine. This India’s favorite red wine has been made with the most ultimate respect for the environment, following strict sustainable practices. Come discover our beautiful vineyard, our Tasting Room and our gorgeous boutique hotel The Source, in the rolling hills of the Nashik Valley.",
    country: "India",
    flavors:
      "Blackberry, black plum, ripe cherry, olives, pepper, mocha with hints of spices.",
    pairings: [
      "Barbecued meats, medium spicy curries like chicken tikka masala",
      "rajma masala, mutton roganjosh",
    ],
    highlights: ["India’s best-selling red wine!"],
    volume: "750ml",
    grapeVarietal: "85% Shiraz, 15% Cabernet Sauvignon.",
  },
  {
    id: 6,
    name: "Sula Tropical Rose",
    img: "/sula/Tropical.png",
    slug: "sula-tropical-rose",
    category: "wines",
    description:
      "Experience Sula’s Tropicale Rosé, India’s first and only Gold winner at the International Wine Challenge. A refreshing burst of tropical fruit and berry flavours, perfect for any celebration. This sparkling wine has been made with the most ultimate respect for the environment, following strict sustainable practices. Come discover our beautiful vineyard, our Tasting Room and our gorgeous boutique hotel The Source, in the rolling hills of Nashik Valley.",
    country: "India",
    flavors:
      "Aromas of peach and passion fruit with hints of guava at the finish.",
    pairings: [
      "Aperitif, salads",
      "fried seafood appetizers, anda masala, white sauce pasta",
    ],
    highlights: ["Special edition sparkling rosé."],
    volume: "750ml",
    grapeVarietal: "70% Chenin Blanc, 30% Riesling and Syrah",
  },
  {
    id: 7,
    name: "Sula Brut",
    img: "/sula/brute.png",
    slug: "sula-brut",
    category: "wines",
    description:
      "Celebrate with Sula Brut, a lively sparkling wine and medalist at the Paris Wine Cup and Decanter Awards. Crisp, refreshing, with citrus and green apple notes—pure joy in every sip. This sparkling white wine has been made with the most ultimate respect for the environment, following strict sustainable practices. Come discover our beautiful vineyard, our Tasting Room and our gorgeous boutique hotel The Source, in the rolling hills of the Nashik Valley.",
    country: "India",
    flavors: "Aromas of apples & pears.",
    pairings: [
      "Salad, French fries",
      "Smoked salmon, fried chicken",
      "Indian pakoras",
      "Hara bhara kebab",
    ],
    highlights: [
      " Light Sparkling Fruity Wine",
      "Versatile wine perfect for everyday",
    ],
    volume: "750ml",
    grapeVarietal: "",
  },
  {
    id: 8,
    name: "Sula Seco",
    img: "/sula/seco.png",
    slug: "sula-seco",
    category: "wines",
    description:
      "Citrusy, delicious and versatile; this is what you can expect from Seco, an endearing sparkling wine, made from Chenin Blanc. This sparkling wine has been made with the most ultimate respect for the environment, following strict sustainable practices. Come discover our beautiful vineyard, our Tasting Room and our gorgeous boutique hotel The Source, in the rolling hills of Nashik Valley.",
    country: "India",
    flavors:
      "Hints of ripe fruit, melon & passion fruit on the palate and a citrusy, lingering finish.",
    pairings: [
      "Aperitifs, frittata",
      "South Asian curries (yellow curry)",
      "Indian pakoras",
    ],
    highlights: [
      "Light sparkling fruity wine",
      "Ideal for sparkling wine cocktails",
      "Perfect for everyday celebrations",
    ],
    volume: "750ml",
    grapeVarietal: "100% Chenin Blanc",
  },
  {
    id: 9,
    name: "Sula Sparkling Shiraz",
    img: "/sula/Sprakling.png",
    slug: "sula-sparkling-shiraz",
    category: "wines",
    description:
      "Uncork Sula’s Sparkling Shiraz, India’s first and only sparkling red wine and a Gold Medal winner at the India Wine Awards. Bold and bursting with rich berry flavours—you won’t want to miss it. This Indian sparkling red wine has been made with the most ultimate respect for the environment, following strict sustainable practices Come discover our beautiful vineyard, our Tasting Room and our gorgeous boutique hotel The Source, in the rolling hills of the Nashik Valley.",
    country: "India",
    flavors: "Pomegranate, dark berries, spices, smoke.",
    pairings: ["Dark chocolate dessert, chili chicken", "dabeli, mutton rahra"],
    highlights: ["Prosecco method for a fruit-forward wine!"],
    volume: "750ml",
    grapeVarietal: "100% Shiraz",
  },
  {
    id: 10,
    name: "Sula Zinfandel Rosé",
    img: "/sula/Rose.png",
    slug: "sula-zinfandel-rose",
    category: "wines",
    description:
      "Citrus, cranberries and ripe fruits notes; this rosé wine has so much to offer. Beautifully made from Zinfandel, its residual sugar is nicely balanced by its refreshing acidity, and offers great freshness. Come discover our beautiful vineyard, our Tasting Room and our gorgeous boutique hotel The Source, in the rolling hills of the Nashik Valley.",
    country: "India",
    flavors: "Intense notes of citrus, cranberry & ripe fruit.",
    pairings: [
      "Salad, Chinese appetizers",
      "Indian pakoras, chicken/ paneer chilli",
    ],
    highlights: [
      "India’s first ever Zinfandel Rosé",
      "Light, resfreshing wine with a great mouthfeel",
      "Perfect for Indian Summers",
      "Value for money",
    ],
    volume: "750ml",
    grapeVarietal: "100% Zinfandel.",
  },
  {
    id: 11,
    name: "Sula Zinfandel Red",
    img: "/sula/Zinfadel.png",
    slug: "sula-zinfandel-red",
    category: "wines",
    description:
      "Generous, fruit-forward and playful, this Zinfandel is a structured and balanced red wine, supported by its delightful plum and dark berries notes. This Zinfandel wine has been made with the most ultimate respect for the environment, following strict sustainable practices. Come discover our beautiful vineyard, our Tasting Room and our gorgeous boutique hotel The Source, in the rolling hills of Nashik Valley.",
    flavors: "Aromas of red berries, blackberries, plums & hints of cinnamon",
    country: "India",
    pairings: ["Curries, cold cuts", "spicy noodles", "teriyaki."],
    highlights: ["India’s first Zinfandel.", "Not aged in barrels."],
    volume: "750ml",
    grapeVarietal: "100% Zinfandel.",
  },
  {
    id: 12,
    name: "Luxardo Maraschino Originale",
    img: "/sula/luxardo_maraschino_originale.png",
    slug: "luxardo-maraschino-originale",
    category: "liqueur",
    description:
      "When Luxardo marasca cherries are harvested at the beginning of every summer, they are put in alcoholic infusion in larch-wood vats together with some leaves and branches of the same trees for up to three years. When ready, both the liquid and the solid parts are distilled in traditional copper pot stills, separating the heart from heads and tails. Only the heart of the distillate is then allowed to mature in ash-wood vats. The last process consists in transforming the distillate in liqueur by adding a simple syrup of water and sugar lowering the ABV to 32%. Crystal clear in colour, the aroma is typical of marasca cherry distillate with strong alcohol spirit and roasted nuttiness, while the taste results smooth but sharp at the same time with hints of dark chocolate, vanilla and orange marmalade. The tall green bottle with its red cap is still hand-plaited in straw within the company, and resembles the Maraschino bottles produced in Zara in the early days, where the straw was placed in order to prevent damage during transportation. Luxardo Maraschino Originale can be enjoyed in many classic cocktails or neat as an after dinner drink. It is also ideal over fruits such as strawberries, pineapples, oranges etc. or as a flavor in confectionary and ice creams.",
    background: "/backgrounds/Maraschino-1.jpg",
    country: "",
    flavors: "",
    pairings: [],
    highlights: ["GMO Free", "Kosher Certified", "Vegan friendly"],
    volume: "750ml",
    alcoholPercentage: "32% alc.by vol.",
  },
  {
    id: 13,
    name: "Luxardo Sambuca",
    img: "/sula/luxardo_sambuca-1.png",
    slug: "luxardo-sambuca",
    category: "liqueur",
    description: "A traditional anise-flavored liqueur from Italy.",
    background: "/backgrounds/sambucabg.jpg",
    country: "",
    flavors: "",
    pairings: [],
    highlights: [],
    volume: "750ml",
  },
  {
    id: 14,
    name: "Luxardo Bitter Rosso",
    img: "/sula/luxardo_bitter.png",
    slug: "luxardo-bitter-rosso",
    category: "liqueur",
    description: "A balanced and aromatic bitter liqueur for cocktails.",
    background: "/backgrounds/bitterbg.jpg",
    country: "",
    flavors: "",
    pairings: [],
    highlights: [],
    volume: "750ml",
  },
  {
    id: 15,
    name: "Luxardo Aperitivo",
    img: "/sula/luxardo_aperitivo.png",
    slug: "luxardo-aperitivo",
    category: "liqueur",
    description: "A refreshing and citrus-forward Italian aperitif.",
    background: "/backgrounds/aperitivobg.jpg",
    country: "",
    flavors: "",
    pairings: [],
    highlights: [],
    volume: "750ml",
  },
  {
    id: 16,
    name: "Luxardo Cherry Liqueur",
    img: "/sula/luxardo-cherry.png",
    slug: "luxardo-cherry-liqueur",
    category: "liqueur",
    description: "A rich cherry liqueur, perfect for classic cocktails.",
    background: "/backgrounds/chreey-bg.jpg",
    country: "",
    flavors: "",
    pairings: [],
    highlights: [],
    volume: "750ml",
  },
  {
    id: 17,
    name: "Luxardo Triple Sec",
    img: "/sula/luxardotriple.jpg",
    slug: "luxardo-triple-sec",
    category: "liqueur",
    description:
      "A high-quality orange liqueur used in cocktails like Margaritas.",
    background: "/backgrounds/triple-sec.jpg",
    country: "",
    flavors: "",
    pairings: [],
    highlights: [],
    volume: "750ml",
  },
  {
    id: 18,
    name: "Luxardo Hazelnut Liqueur",
    img: "/sula/angioletto.png",
    slug: "luxardo-hazelnut-liqueur",
    category: "liqueur",
    description: "A smooth and nutty liqueur, great for dessert cocktails.",
    background: "/home/vodka-bg.jpeg",
    country: "",
    flavors: "",
    pairings: [],
    highlights: [],
    volume: "750ml",
  },
  {
    id: 19,
    name: "Luxardo Absinthe Fata Verde",
    img: "/sula/absinthe.jpg",
    slug: "luxardo-absinthe-fata-verde",
    category: "liqueur",
    description: "A classic absinthe with a strong anise and herbal profile.",
    background: "/home/vodka-bg.jpeg",
    country: "",
    flavors: "",
    pairings: [],
    highlights: [],
    volume: "750ml",
  },
  {
    id: 20,
    name: "Luxardo Rhubarb Bitter",
    img: "/sula/rhubarb.jpg",
    slug: "luxardo-rhubarb-bitter",
    category: "bitter",
    description: "A bittersweet rhubarb-based bitter for unique cocktails.",
    background: "/home/vodka-bg.jpeg",
    country: "",
    flavors: "",
    pairings: [],
    highlights: [],
    volume: "750ml",
  },
  {
    id: 20,
    name: "Luxardo Chamomile Bitter",
    img: "/sula/chamolie.jpg",
    slug: "luxardo-chamomile-bitter",
    category: "bitter",
    description: "A bittersweet rhubarb-based bitter for unique cocktails.",
    background: "/home/vodka-bg.jpeg",
    country: "",
    flavors: "",
    pairings: [],
    highlights: [],
    volume: "750ml",
  },
  {
    id: 20,
    name: "Luxardo Orange Bitter",
    img: "/sula/orange.jpg",
    slug: "luxardo-orange-bitter",
    category: "bitter",
    description: "A bittersweet rhubarb-based bitter for unique cocktails.",
    background: "/home/vodka-bg.jpeg",
    country: "",
    flavors: "",
    pairings: [],
    highlights: [],
    volume: "750ml",
  },
  {
    id: 20,
    name: "Luxardo Coffee Bitter",
    img: "/sula/coffee.jpg",
    slug: "luxardo-coffee-bitter",
    category: "bitter",
    description: "A bittersweet rhubarb-based bitter for unique cocktails.",
    background: "/home/vodka-bg.jpeg",
    country: "",
    flavors: "",
    pairings: [],
    highlights: [],
    volume: "750ml",
  },
];
